pub use crate::core::layout::{
    DIRECTORY_BUCKET_SIZE as TRACE_DIRECTORY_BUCKET_SIZE,
    DIRECTORY_SUB_BUCKET_SIZE as TRACE_DIRECTORY_SUB_BUCKET_SIZE,
};


pub const TRACE_STREAM_PAGE_LOCAL_ID_SPAN: u32 = 4_096;
