use crate::core::layout::LOCAL_ID_BITS;
pub use crate::core::layout::{
    DIRECTORY_BUCKET_SIZE as TRACE_DIRECTORY_BUCKET_SIZE,
    DIRECTORY_SUB_BUCKET_SIZE as TRACE_DIRECTORY_SUB_BUCKET_SIZE,
};

pub const TRACE_LOCAL_ID_MASK: u64 = (1u64 << LOCAL_ID_BITS) - 1;
pub const MAX_TRACE_LOCAL_ID: u32 = TRACE_LOCAL_ID_MASK as u32;

pub const TRACE_STREAM_PAGE_LOCAL_ID_SPAN: u32 = 4_096;
